# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

resources:
  repositories:
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    sdl:
      antimalwareScan:
        enabled: true
      apiscan:
        enabled: true
      armory:
        enabled: true
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true
      codeql:
        compiled:
          enabled: true
      credscan:
        enabled: true
      policheck:
        enabled: true
      psscriptanalyzer:
        enabled: true
      prefast:
        enabled: true
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)\.config\tsaoptions.json
        onboard: false # We already onboarded

    stages:
      - stage: Compliance
        jobs:
          - job: Compliance
            steps:
            - template: /build/templates/build.yml@self
              parameters:
                BuildConfiguration: $(BuildConfiguration)
                BuildPlatform: $(BuildPlatform)
                PublishArtifactTemplate: /build/templates/1es-publish-task.yml@self

            - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
              displayName: Clean up
              condition: succeededOrFailed()
