# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

resources:
  repositories:
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    sdl:
      policheck:
        enabled: true
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true

    stages:
      - stage: Build
        jobs:
          - job: Build
            templateContext:
              mb:
                signing:
                  enabled: true
                  signType: $(SignType)

            steps:
              - template: /build/templates/build.yml@self
                parameters:
                  BuildConfiguration: $(BuildConfiguration)
                  BuildPlatform: $(BuildPlatform)
                  PublishArtifactTemplate: /build/templates/1es-publish-task.yml@self
